import { tempHome } from './test/helpers.mjs'
const tmp = await tempHome(); const db = tmp.openDb(); const store = tmp.store.createStore(db)
const p = store.createNode({ type:'project', name:'P' })
const r = store.createNode({ parentId:p.id, type:'requirement', name:'R' })
store.upsertDocument(r.id,'需求内容','需求正文'); store.upsertDocument(r.id,'概要设计','设计正文')
const tc = store.upsertTestCase(r.id,{name:'回归用例',prompt:'跑单测'})
const rep = store.createTestReport(r.id,{caseId:tc.id,status:'running',kind:'regression'}); store.finishTestReport(rep.id,{status:'pass',summary:'全绿'})
store.upsertAcceptanceSignoff(r.id,{decision:'accepted',comment:'验收通过'})
store.createReleaseItem(r.id,{name:'执行上线 SQL',kind:'sql',status:'done'})
const lint = store.createTestCase(r.id,{name:'静态检查',prompt:'跑 lint',kind:'code_check'})
const g1=store.buildDeliveryGate(r.id)
const st1=store.buildAcceptanceStatus(r.id)
console.log('BEFORE decision=',g1.decision,'acceptanceState=',st1.state)
console.log('  acceptance.totals=',JSON.stringify(st1.report.totals))
const r2=store.createTestReport(r.id,{caseId:lint.id,kind:'code_check',status:'running'}); store.finishTestReport(r2.id,{status:'pass',summary:'无告警'})
const g2=store.buildDeliveryGate(r.id); const st2=store.buildAcceptanceStatus(r.id)
console.log('AFTER  decision=',g2.decision,'acceptanceState=',st2.state)
console.log('  acceptance.totals=',JSON.stringify(st2.report.totals))
console.log('  signoff.stale=',st2.signoff?.stale)
console.log('  sources=',g2.sources.map(s=>`${s.key}=${s.status}`).join(' '))
