import { tempHome } from './test/helpers.mjs'
const tmp = await tempHome(); const db = tmp.openDb(); const store = tmp.store.createStore(db)
const p = store.createNode({ type:'project', name:'P' })
const r = store.createNode({ parentId:p.id, type:'requirement', name:'R' })
store.upsertDocument(r.id,'需求内容','需求正文'); store.upsertDocument(r.id,'概要设计','设计正文')
const tc = store.upsertTestCase(r.id,{name:'回归用例',prompt:'跑单测'})
let rep = store.createTestReport(r.id,{caseId:tc.id,status:'running',kind:'regression'}); store.finishTestReport(rep.id,{status:'pass',summary:'全绿'})
store.upsertAcceptanceSignoff(r.id,{decision:'accepted',comment:'验收通过'})
store.createReleaseItem(r.id,{name:'执行上线 SQL',kind:'sql',status:'done'})
const lint = store.createTestCase(r.id,{name:'静态检查',prompt:'跑 lint',kind:'code_check'})
console.log('1 gate=', store.buildDeliveryGate(r.id).decision, 'acc=', store.buildAcceptanceStatus(r.id).state)
rep = store.createTestReport(r.id,{caseId:lint.id,kind:'code_check',status:'running'}); store.finishTestReport(rep.id,{status:'pass',summary:'无告警'})
console.log('2 gate=', store.buildDeliveryGate(r.id).decision, 'acc=', store.buildAcceptanceStatus(r.id).state, '(stale until re-sign)')
store.upsertAcceptanceSignoff(r.id,{decision:'accepted',comment:'复签'})
const g = store.buildDeliveryGate(r.id)
console.log('3 gate=', g.decision, 'acc=', store.buildAcceptanceStatus(r.id).state)
console.log('  sources=', g.sources.map(s=>`${s.key}=${s.status}`).join(' '))
