/** 稳定错误码：AI 依赖它做自纠，改动需同步设计文档 §9 */
export const CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PARENT_TYPE_INVALID: 'PARENT_TYPE_INVALID',
  LEAF_NODE: 'LEAF_NODE',
  CYCLE_DETECTED: 'CYCLE_DETECTED',
  NOT_FOUND: 'NOT_FOUND',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  PATH_AMBIGUOUS: 'PATH_AMBIGUOUS',
  DOC_NAME_EXISTS: 'DOC_NAME_EXISTS',
  TEST_CASE_NAME_EXISTS: 'TEST_CASE_NAME_EXISTS',
  REPORT_STATUS_IMMUTABLE: 'REPORT_STATUS_IMMUTABLE',
  RELEASE_ITEM_NAME_EXISTS: 'RELEASE_ITEM_NAME_EXISTS',
  CONFIRM_REQUIRED: 'CONFIRM_REQUIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  REPO_NOT_REGISTERED: 'REPO_NOT_REGISTERED',
  REPO_PATH_MISSING: 'REPO_PATH_MISSING',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_EXISTS_DIFFERENT_BASE: 'BRANCH_EXISTS_DIFFERENT_BASE',
  WORKTREE_PATH_EXISTS: 'WORKTREE_PATH_EXISTS',
  MERGE_CONFLICT: 'MERGE_CONFLICT',
  GIT_UNAVAILABLE: 'GIT_UNAVAILABLE',
  GIT_FAILED: 'GIT_FAILED',
  GITLAB_NOT_CONFIGURED: 'GITLAB_NOT_CONFIGURED',
  GITLAB_AUTH_FAILED: 'GITLAB_AUTH_FAILED',
  GITLAB_PROJECT_NOT_FOUND: 'GITLAB_PROJECT_NOT_FOUND',
  GITLAB_UNAVAILABLE: 'GITLAB_UNAVAILABLE',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE'
}

export class AppError extends Error {
  constructor(code, message, details) {
    super(message)
    // name 直接用错误码：String(err) 输出 "PARENT_TYPE_INVALID: …"，
    // 既方便 CLI 直接打印，也让测试里的 assert.throws(fn, /CODE/) 能命中
    this.name = code
    this.code = code
    this.details = details
  }
}

export function fail(code, message, details) {
  throw new AppError(code, message, details)
}
